### PR TITLE
Update badge URL for Travis

### PR DESCRIPTION
**Pull request by jugmac00**
Committed via https://github.com/asottile/all-repos

### CODE REVIEW

**Comment by mgedmin** [comment]
These are trivial and have zero chance of breaking CI.  Does the tooling allow pushing directly to master rather than opening 100+ PRs?

**Comment by jugmac00** [comment]
> These are trivial and have zero chance of breaking CI. Does the tooling allow pushing directly to master rather than opening 100+ PRs?

Yes.

The tool is quite modular, and you even can create your own modules, but merging and pushing to master is builtin.

https://github.com/asottile/all-repos#all_repospushmerge_to_master

That said, I am not sure whether pushing to master is possible in all of Zopefoundation's repositories.

Certainly it is a good idea to discuss how to do a possible next mass pr creation.

**Comment by mgedmin** [comment]
> That said, I am not sure whether pushing to master is possible in all of Zopefoundation's repositories.

It is: branch protections break zest.releaser's workflow.

We mostly don't push directly to master because we want to verify the changes (see CI passing, get reviewer feedback) before integrating them into master.

**Comment by icemac** [comment]
See also the comment of @dataflake to zopefoundation/meta#1.

**Pull request merged**
