### PR TITLE
Drop support for Python < 3.7

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

I see coverage fails because you increased the required percentage from 99.5 to 100.  It is 99.9 when I try it locally.  It misses one [branch in `log.py`](https://github.com/zopefoundation/zope.exceptions/blob/config-with-pure-python-template-fd0d4eae/src/zope/exceptions/log.py#L34).  But when I put a breakpoint in there, I *do* get a pdb prompt, so the code *does* get executed.  Maybe add a 'pragma: no cover' there?

FWIW: Python 3.7 has gone out of security support a few days ago, so for me it would be fine to drop that as well.  But that would be something to decide in `zopefoundation/meta`.

From a Plone perspective: I will release another Plone 5.2 in July and we drop official 3.7 support there, and are already not testing it anymore.  (Plone 6.0 was 3.8+ from the start.)  We try not to break it though, which should be fairly easy because we still support Python 2.7.  Hardest part for someone still wanting to use 5.2 on 3.7, would be to get proper version pins of dependencies, which could have small differences between 3.7 and 3.8.  Anyway, Plone 5.2 would not be using a newer `zope.exceptions` version.

**Comment by jugmac00** [comment]
> Maybe add a 'pragma: no cover' there?

it should be straightforward to add a simple test for that branch, ie construct something that actually ends with a new line

**Comment by icemac** [comment]
> > Maybe add a 'pragma: no cover' there?
> 
> it should be straightforward to add a simple test for that branch, ie construct something that actually ends with a new line

It is not about having something ending in a newline but not ending in one. The existing test does not have a newline in the setup. So this `if` is more line a safeguard, so I decided to change the code a bit to get full coverage via a "trick".

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Comment by icemac** [comment]
> FWIW: Python 3.7 has gone out of security support a few days ago

Thank you @mauritsvanrees for bringing this up. I was not aware that the strong and beloved Python 3.7 is now dead. I created https://github.com/zopefoundation/meta/issues/200 to discuss how to handle end-of-life scenarios in the future.

**Comment by mauritsvanrees** [comment]
> It is not about having something ending in a newline but not ending in one.

Aha, so *that* is what coverage was trying to say with `33->35` as missing: the condition on line 33 is always true in the tests, so line 34 is always executed, but there is no coverage for an immediate jump from line 33 to 35 (an invisible, empty `else` statement).

> The existing test does not have a newline in the setup.

Actually it does.  The `s` in the condition is the output of `print_exception`, which ends with a newline, for example this:

```
'Traceback (most recent call last):\n  File "dummy/filename.py", line 14, in dummy_function\n   - __traceback_info__: Have a Snowman: ☃\nValueError: testing\n'
```

I suppose it is possible that this differs per Python version.

> So this `if` is more line a safeguard, so I decided to change the code a bit to get full coverage via a "trick".

The "trick" definitely makes sense.

**Pull request merged**
